# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def even_fib_sums max
	values = [1, 2]
	while values.last < max
		if (next_value = values[-2] + values[-1]) < max
			values << next_value 
		else
			break
		end
	end
	total = 0
	values.select { |value| value % 2 == 0 }.each { |e| total += e }
	total
end

puts even_fib_sums(4000000)